### ISSUE TITLE
Could not read folder: test/intl...

### ISSUE THREAD

**Issue by nojaf** [rescript-lang/rewatch#131]
Not sure if I should still report issues here, but I keep seeing the log message `Could not read folder: test/intl...`.

Why is it trying to read that folder?

**Comment by hellos3b** [comment]
I see this as well

**Comment by adnelson** [comment]
Not sure if it's the same thing but I was getting similar issues and it was caused by a dead symlink in my folder structure, which caused one of the `fs::metadata` calls inside of `rewatch` to fail. I have a pr #136 that fixes that.

**Comment by rolandpeelen** [comment]
Fixed in https://github.com/rescript-lang/rewatch/pull/140 👌
