### ISSUE TITLE
Rewatch with PNPM doesn't find local packages

### ISSUE THREAD

**Issue by hellos3b** [rescript-lang/rewatch#134]
PNPM monorepos use a `pnpm-workspace.yaml` file to define packages, which can include glob patterns. When running PNPM commands locally or using `--filter @testrepo/dep01`, everything works correctly from the root directory. However, when using Rewatch, these packages fail to resolve.

I've forked the `testrepo` repository and configured it with PNPM: https://github.com/hellos3b/rewatch-pnpm

From my investigation, Yarn hoists all packages to a root `node_modules`, whereas PNPM uses symlinks to cache dependencies as part of its core functionality. If Rewatch is relying on package resolution from `node_modules`, it may be missing the symlinked dependencies.

Since PNPM is included with Node through [Corepack](https://nodejs.org/api/corepack.html), it seems reasonable to add direct support for PNPM resolution.

**Comment by Bushuo** [comment]
I looked through your test repo and compared it to mine.
I am using rewatch together with react native and pnpm so I have `node-linker=hoisted` in the `.npmrc` file.
Maybe it's that.
Also I included all dependencies for packages in my app's `package.json`.
I.e. 
```json
"dependencies": {
    "@testrepo/dep01": "workspace:*"
}
```

**Comment by hellos3b** [comment]
Thanks @Bushuo you put me on the right track, I took a closer look at pnpm's settings and found two very useful properties:

```rc
hoist-workspace-packages=true
public-hoist-pattern[]=@testrepo/*
```

This installs your workspace packages at the root node modules so rescript can find them, without needing to add all packages to your root app (doesn't scale well with large packages)
