### ISSUE TITLE
Fails to compile dependencies written in reasonml

### ISSUE THREAD

**Issue by adnelson** [rescript-lang/rewatch#135]
Our code uses rescript but we depend on various packages that use reason. It seems that these aren't handled by `rewatch`:

```
> yarn rewatch build
[1/7]📦 Building package tree...Could not read folder: src...
[1/7] 📦 Built package tree in 0.01s
[2/7] 🕵️  Found source files in 0.00s
[3/7] 📝 Read compile state 0.00s
[4/7] 🧹 Cleaned 0/0 0.00s
[5/7] ️🛑 Error parsing source files in 0.77s
Error in bs-bastet:
don't know what to do with ../../bastet_js/src/JsFloat.re
Error in relude-parse:
don't know what to do with ../../src/extras/ReludeParse_IPv4.re
Error in relude-parse:
don't know what to do with ../../src/extras/ReludeParse_IPv4.rei
Error in relude:
don't know what to do with ../../src/ior/Relude_Ior_Type.re
Error in relude:
don't know what to do with ../../src/extensions/Relude_Extensions_Applicative.re
Error in relude:
don't know what to do with ../../src/Relude_Map.re
Error in relude:
don't know what to do with ../../src/extensions/Relude_Extensions_Show.re
....
```

Is there anything that can be done to enable support for reason, or is this planned in a subsequent release?

**Comment by zth** [comment]
Reason support was dropped in a fairly recent ReScript version, and Rewatch is designed to work with later versions of ReScript (and will most likely be bundled with the ReScript compiler from v12 and going forward).

**Comment by adnelson** [comment]
Ok... wow that's a surprising decision considering how many packages it will break (and make upgrading to v11 almost impossible for our codebase), but I guess it is what it is.

**Comment by zth** [comment]
Well, most (all?) Reason packages can be autoconverted to ReScript syntax via:
```
npm i -g rescript@9
rescript convert <reason files>
```
I believe most of the popular ecosystem packages that has been converted already was converted this way.

Using this, one could either:
1. Release a new version of the package with ReScript files instead of Reason-files
2. Vendor the converted files in the local project directly

**Comment by adnelson** [comment]
Yeah I think such a thing would be doable although with a large dependency tree it could be cumbersome, but perhaps not so bad.

Another, perhaps stickier issue is the fact that the syntax for curried/uncurried functions is swapped now, which will force us to rewrite quite a lot of code when we want to migrate to v11+. Perhaps there's some kind of script to automatically convert these as well.

**Comment by zth** [comment]
I messaged you on the forum I think, but I'd be happy to hop on a call with you and help figure out what it'd take to upgrade to v11+ for your code base. Feel free to reply on the forums if you're interested.
